services:
  tickets-front:
    image: ghcr.io/zafarumerovkostalegal/tickets-front:latest
    pull_policy: always
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_USE_SESSION_COOKIE: ${VITE_USE_SESSION_COOKIE:-true}
        BUILD_REV: ${BUILD_REV:-unknown}
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
