import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const SKEL_LIST_ROWS = 6;
const SKEL_INBOX_ROWS = 4;
function Shimmer({ className = '', style }) {
    return _jsx("span", { className: `corr-skel__bone${className ? ` ${className}` : ''}`, style: style });
}
export function CorrespondenceHeaderTitleSkeleton({ compact = false }) {
    return (_jsxs("div", { className: "corr-skel__header-text", "aria-hidden": true, children: [_jsx("span", { className: "corr-skel__bone corr-skel__header-h1", style: compact ? { width: '180px', maxWidth: '40%' } : undefined }), !compact && _jsx("span", { className: "corr-skel__bone corr-skel__header-p" })] }));
}
export function CorrespondenceHubSkeleton() {
    return _jsx(CorrespondenceListSkeleton, {});
}
export function CorrespondenceListSkeleton() {
    return (_jsxs("div", { className: "corr-skel corr-skel--list", "aria-busy": "true", "aria-label": "\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430 \u0441\u043F\u0438\u0441\u043A\u0430", children: [_jsx("div", { className: "corr-skel__tabs-row", "aria-hidden": true, children: Array.from({ length: 5 }).map((_, i) => (_jsx(Shimmer, { className: "corr-skel__tab-pill", style: { width: `${64 + i * 6}px` } }, i))) }), _jsx("div", { className: "corr-skel__list", "aria-hidden": true, children: Array.from({ length: SKEL_LIST_ROWS }).map((_, row) => (_jsxs("div", { className: "corr-skel__list-item", children: [_jsxs("div", { className: "corr-skel__list-start", children: [_jsx(Shimmer, { className: "corr-skel__list-num" }), _jsxs("div", { className: "corr-skel__list-main", children: [_jsx(Shimmer, { className: "corr-skel__list-subject", style: { width: `${55 + (row % 3) * 12}%` } }), _jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--sm", style: { width: '38%' } })] })] }), _jsxs("div", { className: "corr-skel__list-end", children: [_jsx(Shimmer, { className: "corr-skel__badge" }), _jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--sm", style: { width: '72px' } })] })] }, row))) })] }));
}
export function CorrespondenceComposeSkeleton() {
    return (_jsx("div", { className: "corr-skel corr-skel--compose", "aria-busy": "true", "aria-label": "\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430 \u0444\u043E\u0440\u043C\u044B", children: _jsxs("div", { className: "corr-skel__compose-paper", "aria-hidden": true, children: [Array.from({ length: 2 }).map((_, i) => (_jsxs("div", { className: "corr-skel__field", children: [_jsx(Shimmer, { className: "corr-skel__field-label" }), _jsx(Shimmer, { className: "corr-skel__field-input" })] }, i))), _jsxs("div", { className: "corr-skel__field", children: [_jsx(Shimmer, { className: "corr-skel__field-label" }), _jsx(Shimmer, { className: "corr-skel__field-textarea" })] }), _jsxs("div", { className: "corr-skel__field", children: [_jsx(Shimmer, { className: "corr-skel__field-label" }), _jsx(Shimmer, { className: "corr-skel__field-btn" })] })] }) }));
}
export function CorrespondencePreviewSkeleton() {
    return (_jsxs("div", { className: "corr-skel corr-skel--preview", "aria-busy": "true", "aria-label": "\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430", children: [_jsx(Shimmer, { className: "corr-skel__banner" }), _jsxs("div", { className: "corr-skel__doc", "aria-hidden": true, children: [_jsxs("div", { className: "corr-skel__doc-head", children: [_jsxs("div", { className: "corr-skel__doc-logo", children: [_jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--lg", style: { width: '120px' } }), _jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--sm", style: { width: '90px' } })] }), _jsxs("div", { className: "corr-skel__doc-meta", children: [_jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--sm", style: { width: '100px' } }), _jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--sm", style: { width: '80px' } })] })] }), _jsx(Shimmer, { className: "corr-skel__doc-hr" }), _jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--md", style: { width: '45%' } }), _jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--lg", style: { width: '70%', marginTop: '1.25rem' } }), Array.from({ length: 5 }).map((_, i) => (_jsx(Shimmer, { className: "corr-skel__doc-line", style: { width: `${88 - (i % 3) * 8}%` } }, i))), _jsx(Shimmer, { className: "corr-skel__doc-line", style: { width: '52%' } })] })] }));
}
export function CorrespondenceInboxSkeleton() {
    return (_jsx("div", { className: "corr-skel corr-skel--inbox", "aria-busy": "true", "aria-label": "\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430 \u0432\u0445\u043E\u0434\u044F\u0449\u0438\u0445", children: _jsx("div", { className: "corr-skel__inbox-list", "aria-hidden": true, children: Array.from({ length: SKEL_INBOX_ROWS }).map((_, row) => (_jsxs("div", { className: "corr-skel__inbox-item", children: [_jsx(Shimmer, { className: "corr-skel__inbox-dot" }), _jsxs("div", { className: "corr-skel__inbox-body", children: [_jsxs("div", { className: "corr-skel__inbox-row1", children: [_jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--sm", style: { width: '72px' } }), _jsx(Shimmer, { className: "corr-skel__badge corr-skel__badge--sm" })] }), _jsx(Shimmer, { className: "corr-skel__list-subject", style: { width: `${60 + (row % 2) * 15}%` } }), _jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--sm", style: { width: '48%' } })] }), _jsx(Shimmer, { className: "corr-skel__badge" })] }, row))) }) }));
}
export const CorrespondenceMainSkeleton = CorrespondenceHubSkeleton;
export function CorrespondenceRegistrySkeleton({ rows = 6 }) {
    return (_jsxs("div", { className: "corr-skel corr-skel--registry", "aria-busy": "true", "aria-label": "\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430 \u0440\u0435\u0435\u0441\u0442\u0440\u0430", children: [_jsx("div", { className: "corr-skel__stats", "aria-hidden": true, children: Array.from({ length: 4 }).map((_, i) => (_jsxs("div", { className: "corr-skel__stat", children: [_jsx(Shimmer, { className: "corr-skel__stat-icon" }), _jsxs("div", { className: "corr-skel__stat-text", children: [_jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--sm" }), _jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--lg" }), _jsx(Shimmer, { className: "corr-skel__stat-line corr-skel__stat-line--sm", style: { width: '40%' } })] })] }, i))) }), _jsxs("div", { className: "corr-skel__table-card", "aria-hidden": true, children: [_jsxs("div", { className: "corr-skel__toolbar", children: [_jsx("div", { className: "corr-skel__tabs", children: Array.from({ length: 4 }).map((_, i) => (_jsx(Shimmer, { className: "corr-skel__tab", style: { width: `${56 + i * 8}px` } }, i))) }), _jsxs("div", { className: "corr-skel__toolbar-actions", children: [_jsx(Shimmer, { className: "corr-skel__btn" }), _jsx(Shimmer, { className: "corr-skel__icon-btn" })] })] }), _jsxs("div", { className: "corr-skel__table-wrap", children: [_jsx("div", { className: "corr-skel__thead", children: ['48px', '88px', '72px', '1fr', '56px', '64px', '72px', '56px', '24px'].map((w, i) => (_jsx(Shimmer, { className: `corr-skel__th${w === '1fr' ? ' corr-skel__th--grow' : ''}`, style: w !== '1fr' ? { width: w } : undefined }, i))) }), Array.from({ length: rows }).map((_, row) => (_jsxs("div", { className: "corr-skel__tr", children: [_jsx(Shimmer, { className: "corr-skel__td", style: { width: '72px' } }), _jsx(Shimmer, { className: "corr-skel__td", style: { width: '88px' } }), _jsx(Shimmer, { className: "corr-skel__td", style: { width: '80px' } }), _jsx(Shimmer, { className: "corr-skel__td corr-skel__td--subject", style: { width: `${45 + (row % 3) * 12}%` } }), _jsx(Shimmer, { className: "corr-skel__td", style: { width: '52px' } }), _jsx(Shimmer, { className: "corr-skel__td", style: { width: '28px' } }), _jsx(Shimmer, { className: "corr-skel__td", style: { width: '96px' } }), _jsx(Shimmer, { className: "corr-skel__td", style: { width: '72px' } }), _jsx(Shimmer, { className: "corr-skel__td", style: { width: '56px' } }), _jsx(Shimmer, { className: "corr-skel__td", style: { width: '20px' } })] }, row)))] }), _jsxs("div", { className: "corr-skel__footer", children: [_jsx(Shimmer, { className: "corr-skel__footer-meta" }), _jsxs("div", { className: "corr-skel__pager", children: [_jsx(Shimmer, { className: "corr-skel__page-arrow" }), _jsx(Shimmer, { className: "corr-skel__page-num" }), _jsx(Shimmer, { className: "corr-skel__page-arrow" })] })] })] })] }));
}
export function CorrespondenceRegistrySkeletonLegacy() {
    return _jsx(CorrespondenceListSkeleton, {});
}
export function CorrespondenceAsideSkeleton() {
    return (_jsxs("div", { className: "corr-skel corr-skel--aside", "aria-hidden": true, children: [_jsx(Shimmer, { className: "corr-skel__aside-title" }), _jsx(Shimmer, { className: "corr-skel__aside-btn corr-skel__aside-btn--primary" }), _jsx(Shimmer, { className: "corr-skel__aside-btn" })] }));
}
export function CorrespondenceScreenSkeleton({ kind }) {
    switch (kind) {
        case 'incoming':
        case 'outgoing':
            return null;
        case 'compose':
            return _jsx(CorrespondenceComposeSkeleton, {});
        case 'preview':
        case 'partner-review':
            return _jsx(CorrespondencePreviewSkeleton, {});
    }
}
