import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import './VacationScheduleSkeleton.css';
const LEGEND_PLACEHOLDERS = 5;
const HEADER_MONTH_BLOCKS = 6;
const DAY_CELLS_PREVIEW = 48;
const BODY_ROWS = 8;
export function VacationScheduleSkeleton() {
    return (_jsxs("div", { className: "vac-skel", "aria-busy": "true", "aria-label": "\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430 \u0442\u0430\u0431\u043B\u0438\u0446\u044B \u0433\u0440\u0430\u0444\u0438\u043A\u0430 \u043E\u0442\u043F\u0443\u0441\u043A\u043E\u0432", children: [_jsx("div", { className: "vac-skel__legend", children: Array.from({ length: LEGEND_PLACEHOLDERS }).map((_, i) => (_jsx("span", { className: "vac-skel__chip" }, i))) }), _jsx("div", { className: "vac-skel__scroll", children: _jsxs("div", { className: "vac-skel__table", children: [_jsxs("div", { className: "vac-skel__thead", children: [_jsxs("div", { className: "vac-skel__tr vac-skel__tr--months", children: [_jsx("div", { className: "vac-skel__corner" }), _jsxs("div", { className: "vac-skel__months-strip", children: [Array.from({ length: HEADER_MONTH_BLOCKS }).map((_, i) => (_jsx("span", { className: "vac-skel__month-block" }, i))), _jsx("span", { className: "vac-skel__sum-pill" })] })] }), _jsxs("div", { className: "vac-skel__tr vac-skel__tr--nums", children: [_jsx("span", { className: "vac-skel__th-num" }), _jsx("span", { className: "vac-skel__th-name" }), _jsx("div", { className: "vac-skel__day-strip", children: Array.from({ length: DAY_CELLS_PREVIEW }).map((_, i) => (_jsx("span", { className: "vac-skel__day-head" }, i))) })] }), _jsxs("div", { className: "vac-skel__tr vac-skel__tr--wd", children: [_jsx("span", { className: "vac-skel__th-num vac-skel__th-num--ghost" }), _jsx("span", { className: "vac-skel__th-name vac-skel__th-name--ghost" }), _jsx("div", { className: "vac-skel__day-strip", children: Array.from({ length: DAY_CELLS_PREVIEW }).map((_, i) => (_jsx("span", { className: "vac-skel__wd-head" }, i))) })] })] }), _jsx("div", { className: "vac-skel__tbody", children: Array.from({ length: BODY_ROWS }).map((_, row) => (_jsxs("div", { className: "vac-skel__tr vac-skel__tr--body", children: [_jsx("span", { className: "vac-skel__td-num" }), _jsx("span", { className: "vac-skel__td-name" }), _jsx("div", { className: "vac-skel__day-strip", children: Array.from({ length: DAY_CELLS_PREVIEW }).map((_, col) => (_jsx("span", { className: "vac-skel__cell" }, col))) })] }, row))) })] }) })] }));
}
