import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { VACATION_MONTH_NAMES } from '../lib/vacationScheduleModel';
const STATUSES = [
    { id: 'all', label: 'Все' },
    { id: 'away', label: 'Согласованы' },
    { id: 'planned', label: 'Ожидают' },
    { id: 'declined', label: 'Отклонены' },
];
export function VacationCalendarFilters({ year, onYearChange, status, onStatusChange, monthOpen, monthIndex, onMonthStep, onShowYear, onShowMonth, legend, kindCounts, hiddenKinds, onToggleKind, lates = null, }) {
    return (_jsxs("div", { className: "vac-toolbar", "aria-label": "\u0424\u0438\u043B\u044C\u0442\u0440\u044B \u043A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044F", children: [_jsxs("div", { className: "vac-toolbar__controls", children: [_jsxs("div", { className: "vac-filters__year", children: [_jsx("button", { type: "button", "aria-label": monthOpen ? 'Предыдущий месяц' : 'Предыдущий год', onClick: () => (monthOpen ? onMonthStep(-1) : onYearChange(year - 1)), disabled: !monthOpen && year <= 2000, children: "\u2039" }), _jsx("span", { children: monthIndex != null ? `${VACATION_MONTH_NAMES[monthIndex]} ${year}` : year }), _jsx("button", { type: "button", "aria-label": monthOpen ? 'Следующий месяц' : 'Следующий год', onClick: () => (monthOpen ? onMonthStep(1) : onYearChange(year + 1)), disabled: !monthOpen && year >= 2100, children: "\u203A" })] }), _jsx("div", { className: "vac-filters__chips", role: "group", "aria-label": "\u0421\u0442\u0430\u0442\u0443\u0441 \u043E\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0438\u044F", children: STATUSES.map((item) => (_jsx("button", { type: "button", className: `vac-filters__chip vac-filters__chip--${item.id}${status === item.id ? ' vac-filters__chip--on' : ''}`, "aria-pressed": status === item.id, onClick: () => onStatusChange(item.id), children: item.label }, item.id))) }), _jsxs("div", { className: "vac-filters__modes", role: "group", "aria-label": "\u0420\u0435\u0436\u0438\u043C \u043F\u0440\u043E\u0441\u043C\u043E\u0442\u0440\u0430", children: [_jsx("button", { type: "button", className: `vac-filters__mode${!monthOpen ? ' vac-filters__mode--on' : ''}`, "aria-pressed": !monthOpen, onClick: onShowYear, children: "\u0413\u043E\u0434" }), _jsx("button", { type: "button", className: `vac-filters__mode${monthOpen ? ' vac-filters__mode--on' : ''}`, "aria-pressed": monthOpen, onClick: onShowMonth, children: "\u041C\u0435\u0441\u044F\u0446" })] })] }), (legend.some((item) => (kindCounts.get(item.kind) ?? 0) > 0) || (lates && lates.count > 0)) ? (_jsxs("div", { className: "vac-toolbar__legend", role: "group", "aria-label": "\u041B\u0435\u0433\u0435\u043D\u0434\u0430", children: [legend.filter((item) => (kindCounts.get(item.kind) ?? 0) > 0).map((item) => {
                        const hidden = hiddenKinds.has(item.kind);
                        return (_jsxs("button", { type: "button", className: `vac-filters__legend-row${hidden ? ' vac-filters__legend-row--off' : ''}`, "aria-pressed": !hidden, title: hidden ? `Показать: ${item.label}` : `Скрыть: ${item.label}`, onClick: () => onToggleKind(item.kind), children: [_jsx("i", { style: { background: item.color }, "aria-hidden": true }), _jsx("span", { children: item.label }), _jsx("b", { children: kindCounts.get(item.kind) ?? 0 })] }, item.kind));
                    }), lates && lates.count > 0 ? (_jsxs("button", { type: "button", className: `vac-filters__legend-row${lates.hidden ? ' vac-filters__legend-row--off' : ''}`, "aria-pressed": !lates.hidden, title: lates.hidden ? 'Показать опоздания' : 'Скрыть опоздания', onClick: lates.onToggle, children: [_jsx("i", { style: { background: '#b45309' }, "aria-hidden": true }), _jsx("span", { children: "\u041E\u043F\u043E\u0437\u0434\u0430\u043D\u0438\u0435" }), _jsx("b", { children: lates.count })] })) : null] })) : null] }));
}
