import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { contactAvatarColor, contactInitials, mailHref, telHref } from '../lib/contactsModel';
function IconPhone() {
    return (_jsx("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", "aria-hidden": true, children: _jsx("path", { d: "M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z" }) }));
}
function IconMail() {
    return (_jsxs("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", "aria-hidden": true, children: [_jsx("path", { d: "M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" }), _jsx("polyline", { points: "22,6 12,13 2,6" })] }));
}
export function ContactBusinessCard({ card, youBadge, primaryBadge, saveLabel, isYou, onSave, preview = false, }) {
    const tel = card.phone ? telHref(card.phone) : null;
    const mail = card.email ? mailHref(card.email) : null;
    const canSave = Boolean(onSave && (card.phone || card.email));
    return (_jsxs("article", { className: `contacts-card contacts-card--${card.kind}${preview ? ' contacts-card--preview' : ''}`, children: [_jsx("div", { className: "contacts-card__accent", style: { background: contactAvatarColor(card.name) }, "aria-hidden": true }), _jsxs("div", { className: "contacts-card__body", children: [_jsxs("div", { className: "contacts-card__head", children: [card.picture ? (_jsx("img", { className: "contacts-card__avatar contacts-card__avatar--photo", src: card.picture, alt: "" })) : (_jsx("span", { className: "contacts-card__avatar", style: { background: contactAvatarColor(card.name) }, "aria-hidden": true, children: contactInitials(card.name) })), _jsxs("div", { className: "contacts-card__identity", children: [_jsxs("h3", { className: "contacts-card__name", children: [card.name, isYou && youBadge ? _jsx("span", { className: "contacts-card__you", children: youBadge }) : null] }), card.subtitle ? _jsx("p", { className: "contacts-card__subtitle", children: card.subtitle }) : null, card.isPrimary && primaryBadge ? (_jsx("span", { className: "contacts-card__badge", children: primaryBadge })) : null] })] }), _jsxs("ul", { className: "contacts-card__rows", children: [card.phone ? (_jsxs("li", { className: "contacts-card__row", children: [_jsx("span", { className: "contacts-card__row-icon", children: _jsx(IconPhone, {}) }), tel ? (_jsx("a", { className: "contacts-card__row-link", href: tel, children: card.phone })) : (_jsx("span", { className: "contacts-card__row-text", children: card.phone }))] })) : null, card.email ? (_jsxs("li", { className: "contacts-card__row", children: [_jsx("span", { className: "contacts-card__row-icon", children: _jsx(IconMail, {}) }), mail ? (_jsx("a", { className: "contacts-card__row-link", href: mail, children: card.email })) : (_jsx("span", { className: "contacts-card__row-text", children: card.email }))] })) : null] }), canSave && !preview ? (_jsx("button", { type: "button", className: "contacts-card__save", onClick: onSave, children: saveLabel })) : null] })] }));
}
