import { Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useId, useRef, useState } from 'react';
import { PERIOD_OPTIONS } from '@entities/time-tracking/model/reportsPanelConfig';
import { DatePicker } from '@shared/ui/DatePicker';
import { useI18n, ttReportPeriodLabel } from '@shared/i18n';
import { formatIsoDateLabel } from '@entities/time-tracking/lib/reportsPeriodRange';
import { ReportsUserFilterDropdown } from '@pages/time-tracking/ui/ReportsUserFilterDropdown';
import { ReportPreviewTeamFilter } from './ReportPreviewTeamFilter';
const IcoChevLeft = () => (_jsx("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2.25", strokeLinecap: "round", "aria-hidden": true, children: _jsx("path", { d: "M15 18l-6-6 6-6" }) }));
const IcoChevRight = () => (_jsx("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2.25", strokeLinecap: "round", "aria-hidden": true, children: _jsx("path", { d: "M9 18l6-6-6-6" }) }));
const IcoChevDown = () => (_jsx("svg", { width: "12", height: "12", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2.25", strokeLinecap: "round", "aria-hidden": true, children: _jsx("path", { d: "M6 9l6 6 6-6" }) }));
const IcoCal = () => (_jsxs("svg", { width: "15", height: "15", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": true, children: [_jsx("rect", { x: "3", y: "4", width: "18", height: "18", rx: "2" }), _jsx("path", { d: "M16 2v4M8 2v4M3 10h18" })] }));
export function ReportPreviewFiltersBar({ periodTitle, periodGranularity, onPeriodGranularityChange, onPrevPeriod, onNextPeriod, users, usersError, selectedUserIds, onSelectedUserIdsChange, dateFrom, dateTo, onDateFromChange, onDateToChange, customRangeActive, onResetCustomRange, disabled = false, hidePeriodControls = false, teamFilter, actionsSlot, }) {
    const { t } = useI18n();
    const rangeId = useId();
    const [periodDropdown, setPeriodDropdown] = useState(false);
    const [datesOpen, setDatesOpen] = useState(false);
    const periodDropdownRef = useRef(null);
    useEffect(() => {
        if (!periodDropdown || hidePeriodControls)
            return;
        const h = (e) => {
            if (periodDropdownRef.current?.contains(e.target))
                return;
            setPeriodDropdown(false);
        };
        document.addEventListener('mousedown', h);
        return () => document.removeEventListener('mousedown', h);
    }, [periodDropdown, hidePeriodControls]);
    const periodChipLabel = `${formatIsoDateLabel(dateFrom)} — ${formatIsoDateLabel(dateTo)}`;
    const toolbarTitle = customRangeActive || hidePeriodControls
        ? periodTitle
        : (periodTitle.includes(':') ? periodTitle.slice(0, periodTitle.indexOf(':')).trim() : periodTitle);
    return (_jsxs("div", { className: `tt-rp-preview__filters tt-rp-preview__filters--toolbar${hidePeriodControls ? ' tt-rp-preview__filters--period-locked' : ''}`, children: [_jsxs("div", { className: "tt-rp-preview__toolbar", role: "toolbar", "aria-label": "\u041F\u0435\u0440\u0438\u043E\u0434 \u0438 \u0444\u0438\u043B\u044C\u0442\u0440\u044B \u043E\u0442\u0447\u0451\u0442\u0430", children: [_jsx("div", { className: "tt-rp-preview__toolbar-period", children: hidePeriodControls ? (_jsxs(_Fragment, { children: [_jsx("h2", { className: "tt-rp-preview__toolbar-title", title: periodTitle, children: toolbarTitle }), _jsxs("span", { className: "tt-rp-preview__toolbar-chip tt-rp-preview__toolbar-chip--static", title: periodChipLabel, children: [_jsx(IcoCal, {}), _jsx("span", { className: "tt-rp-preview__toolbar-chip-text", children: periodChipLabel })] })] })) : (_jsxs(_Fragment, { children: [_jsx("button", { type: "button", className: "tt-rp-preview__toolbar-nav", onClick: onPrevPeriod, disabled: disabled || periodGranularity === 'all', "aria-label": t('timeTrackingPage.reports.header.prevPeriod'), children: _jsx(IcoChevLeft, {}) }), _jsx("h2", { className: "tt-rp-preview__toolbar-title", title: periodTitle, children: toolbarTitle }), _jsx("button", { type: "button", className: "tt-rp-preview__toolbar-nav", onClick: onNextPeriod, disabled: disabled || periodGranularity === 'all', "aria-label": t('timeTrackingPage.reports.header.nextPeriod'), children: _jsx(IcoChevRight, {}) }), _jsxs("div", { className: "tt-reports__period-dropdown-wrap tt-rp-preview__toolbar-granularity", ref: periodDropdownRef, children: [_jsxs("button", { type: "button", className: "tt-rp-preview__toolbar-chip tt-rp-preview__toolbar-chip--ghost", disabled: disabled, onClick: () => !disabled && setPeriodDropdown((v) => !v), "aria-expanded": periodDropdown, title: "\u0422\u0438\u043F \u043F\u0435\u0440\u0438\u043E\u0434\u0430", children: [ttReportPeriodLabel(periodGranularity, t), _jsx(IcoChevDown, {})] }), periodDropdown && !disabled && (_jsx("div", { className: "tt-reports__period-dropdown", role: "listbox", children: PERIOD_OPTIONS.map((opt) => (_jsx("button", { type: "button", role: "option", "aria-selected": periodGranularity === opt.id, className: `tt-reports__period-opt${periodGranularity === opt.id ? ' tt-reports__period-opt--active' : ''}`, onClick: () => {
                                                    onPeriodGranularityChange(opt.id);
                                                    setPeriodDropdown(false);
                                                }, children: ttReportPeriodLabel(opt.id, t) }, opt.id))) }))] }), _jsxs("button", { type: "button", className: `tt-rp-preview__toolbar-chip${datesOpen || customRangeActive ? ' tt-rp-preview__toolbar-chip--active' : ''}`, disabled: disabled, onClick: () => !disabled && setDatesOpen((v) => !v), "aria-expanded": datesOpen, title: t('timeTrackingPage.reports.dateRange.aria'), children: [_jsx(IcoCal, {}), _jsx("span", { className: "tt-rp-preview__toolbar-chip-text", children: periodChipLabel })] })] })) }), _jsx("div", { className: "tt-rp-preview__toolbar-sep", "aria-hidden": true }), _jsxs("div", { className: "tt-rp-preview__toolbar-filters", children: [usersError ? (_jsx("p", { className: "tt-reports__users-filter-err", role: "status", children: usersError })) : null, teamFilter ? (_jsx(ReportPreviewTeamFilter, { ...teamFilter, disabled: disabled })) : null, _jsx(ReportsUserFilterDropdown, { users: users, selected: selectedUserIds, onChange: onSelectedUserIdsChange, disabled: disabled })] }), actionsSlot ? (_jsx("div", { className: "tt-rp-preview__toolbar-actions", children: actionsSlot })) : null] }), !hidePeriodControls && datesOpen ? (_jsxs("div", { className: "tt-rp-preview__dates-panel", "aria-label": t('timeTrackingPage.reports.dateRange.aria'), children: [_jsxs("div", { className: "tt-reports__date-field", children: [_jsx("span", { className: "tt-reports__date-field-label", id: `${rangeId}-from`, children: t('timeTrackingPage.reports.dateRange.from') }), _jsx(DatePicker, { value: dateFrom, max: dateTo, onChange: onDateFromChange, disabled: disabled, "aria-labelledby": `${rangeId}-from`, portal: true, buttonClassName: "tt-reports__date-picker-btn" })] }), _jsxs("div", { className: "tt-reports__date-field", children: [_jsx("span", { className: "tt-reports__date-field-label", id: `${rangeId}-to`, children: t('timeTrackingPage.reports.dateRange.to') }), _jsx(DatePicker, { value: dateTo, min: dateFrom, onChange: onDateToChange, disabled: disabled, "aria-labelledby": `${rangeId}-to`, portal: true, buttonClassName: "tt-reports__date-picker-btn" })] }), customRangeActive && !disabled ? (_jsx("button", { type: "button", className: "tt-reports__btn tt-reports__btn--outline", onClick: onResetCustomRange, children: t('timeTrackingPage.reports.dateRange.backToPeriod').replace('{period}', ttReportPeriodLabel(periodGranularity, t).toLowerCase()) })) : null] })) : null] }));
}
