import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
function Skel({ className = '' }) {
    return _jsx("span", { className: `kd-tg-skel ${className}`.trim(), "aria-hidden": true });
}
export function KostaDailyChatListSkeleton({ rows = 7 }) {
    return (_jsx("ul", { className: "kd-tg-skel-list kd-tg-skel-list--chats", role: "list", "aria-hidden": true, children: Array.from({ length: rows }, (_, i) => (_jsxs("li", { className: "kd-tg-skel-chat-row", role: "listitem", children: [_jsx(Skel, { className: "kd-tg-skel--circle kd-tg-skel--avatar-lg" }), _jsxs("span", { className: "kd-tg-skel-chat-row__body", children: [_jsxs("span", { className: "kd-tg-skel-chat-row__top", children: [_jsx(Skel, { className: "kd-tg-skel--title" }), _jsx(Skel, { className: "kd-tg-skel--time" })] }), _jsxs("span", { className: "kd-tg-skel-chat-row__bottom", children: [_jsx(Skel, { className: "kd-tg-skel--preview" }), i < 2 ? _jsx(Skel, { className: "kd-tg-skel--badge" }) : null] })] })] }, i))) }));
}
export function KostaDailyMembersSkeleton({ rows = 10 }) {
    return (_jsx("ul", { className: "kd-tg-skel-list kd-tg-skel-list--members", role: "list", "aria-hidden": true, children: Array.from({ length: rows }, (_, i) => (_jsxs("li", { className: "kd-tg-skel-member-row", role: "listitem", children: [_jsx(Skel, { className: "kd-tg-skel--circle kd-tg-skel--avatar-md" }), _jsxs("span", { className: "kd-tg-skel-member-row__body", children: [_jsx(Skel, { className: "kd-tg-skel--name" }), _jsx(Skel, { className: "kd-tg-skel--meta" }), _jsx(Skel, { className: "kd-tg-skel--email" })] })] }, i))) }));
}
export function KostaDailyChatPaneSkeleton() {
    return (_jsxs("div", { className: "kd-tg-skel-pane", "aria-hidden": true, children: [_jsxs("header", { className: "kd-tg-skel-pane__head", children: [_jsx(Skel, { className: "kd-tg-skel--circle kd-tg-skel--avatar-sm" }), _jsxs("span", { className: "kd-tg-skel-pane__head-text", children: [_jsx(Skel, { className: "kd-tg-skel--head-title" }), _jsx(Skel, { className: "kd-tg-skel--head-sub" })] }), _jsxs("span", { className: "kd-tg-skel-pane__head-actions", children: [_jsx(Skel, { className: "kd-tg-skel--icon" }), _jsx(Skel, { className: "kd-tg-skel--icon" })] })] }), _jsxs("div", { className: "kd-tg-skel-pane__messages", children: [_jsx("div", { className: "kd-tg-skel-date", children: _jsx(Skel, { className: "kd-tg-skel--date-pill" }) }), _jsxs("div", { className: "kd-tg-skel-msg kd-tg-skel-msg--in", children: [_jsx(Skel, { className: "kd-tg-skel--circle kd-tg-skel--avatar-xs" }), _jsxs("span", { className: "kd-tg-skel-bubble kd-tg-skel-bubble--in", children: [_jsx(Skel, { className: "kd-tg-skel--name-inline" }), _jsx(Skel, { className: "kd-tg-skel--line kd-tg-skel--line-w90" }), _jsx(Skel, { className: "kd-tg-skel--line kd-tg-skel--line-w70" })] })] }), _jsxs("div", { className: "kd-tg-skel-msg kd-tg-skel-msg--in kd-tg-skel-msg--grouped", children: [_jsx("span", { className: "kd-tg-skel-msg__avatar-slot" }), _jsx("span", { className: "kd-tg-skel-bubble kd-tg-skel-bubble--in kd-tg-skel-bubble--short", children: _jsx(Skel, { className: "kd-tg-skel--line kd-tg-skel--line-w55" }) })] }), _jsxs("div", { className: "kd-tg-skel-msg kd-tg-skel-msg--in", children: [_jsx(Skel, { className: "kd-tg-skel--circle kd-tg-skel--avatar-xs" }), _jsxs("span", { className: "kd-tg-skel-bubble kd-tg-skel-bubble--in", children: [_jsx(Skel, { className: "kd-tg-skel--name-inline" }), _jsx(Skel, { className: "kd-tg-skel--line kd-tg-skel--line-w80" })] })] }), _jsx("div", { className: "kd-tg-skel-msg kd-tg-skel-msg--out", children: _jsxs("span", { className: "kd-tg-skel-bubble kd-tg-skel-bubble--out", children: [_jsx(Skel, { className: "kd-tg-skel--line kd-tg-skel--line-w75" }), _jsx(Skel, { className: "kd-tg-skel--line kd-tg-skel--line-w45" })] }) }), _jsx("div", { className: "kd-tg-skel-msg kd-tg-skel-msg--out kd-tg-skel-msg--grouped", children: _jsx("span", { className: "kd-tg-skel-bubble kd-tg-skel-bubble--out kd-tg-skel-bubble--short", children: _jsx(Skel, { className: "kd-tg-skel--line kd-tg-skel--line-w60" }) }) }), _jsxs("div", { className: "kd-tg-skel-msg kd-tg-skel-msg--in", children: [_jsx(Skel, { className: "kd-tg-skel--circle kd-tg-skel--avatar-xs" }), _jsxs("span", { className: "kd-tg-skel-bubble kd-tg-skel-bubble--in", children: [_jsx(Skel, { className: "kd-tg-skel--name-inline" }), _jsx(Skel, { className: "kd-tg-skel--line kd-tg-skel--line-w95" }), _jsx(Skel, { className: "kd-tg-skel--line kd-tg-skel--line-w65" })] })] })] }), _jsx("footer", { className: "kd-tg-skel-pane__composer", children: _jsx(Skel, { className: "kd-tg-skel--composer-bar" }) })] }));
}
