import { Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {} from '@entities/time-tracking';
import { useI18n } from '@shared/i18n';
import { fmtH, fmtAmt } from '@entities/time-tracking/lib/reportsFormatUtils';
import { IcoExpand } from './reportsDetailWidgets';
function UninvoicedUserRows({ users, currency }) {
    return (_jsx(_Fragment, { children: users.map((u) => (_jsxs("tr", { className: "rp-table__sub-row", children: [_jsxs("td", { className: "rp-table__sub-indent", colSpan: 3, children: [_jsx("span", { className: "rp-table__sub-icon", children: "\u21B3" }), _jsx("span", { children: u.user_name })] }), _jsx("td", { className: "rp-table__num", children: fmtH(u.uninvoiced_hours) }), _jsx("td", { className: "rp-table__num", children: fmtAmt(u.uninvoiced_amount, u.currency ?? currency) }), _jsx("td", {}), _jsx("td", {})] }, u.user_id))) }));
}
export function UninvoicedTable({ rows, expanded, onToggle, }) {
    const { t } = useI18n();
    return (_jsxs("table", { className: "tt-reports__table rp-table", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: t('timeTrackingPage.reports.uninvoicedTable.project') }), _jsx("th", { children: t('timeTrackingPage.reports.uninvoicedTable.client') }), _jsx("th", { children: t('timeTrackingPage.reports.uninvoicedTable.currency') }), _jsx("th", { className: "rp-table__num", children: t('timeTrackingPage.reports.uninvoicedTable.billableHours') }), _jsx("th", { className: "rp-table__num", children: t('timeTrackingPage.reports.uninvoicedTable.uninvoicedHours') }), _jsx("th", { className: "rp-table__num", children: t('timeTrackingPage.reports.uninvoicedTable.uninvoicedAmount') }), _jsx("th", { className: "rp-table__num", children: t('timeTrackingPage.reports.uninvoicedTable.uninvoicedExpenses') }), _jsx("th", { className: "rp-table__expand-col", "aria-label": t('timeTrackingPage.reports.table.expand') })] }) }), _jsx("tbody", { children: rows.map((r) => {
                    const key = r.project_id;
                    const isOpen = expanded.has(key);
                    return (_jsxs(_Fragment, { children: [_jsxs("tr", { className: "rp-table__group-row", onClick: () => r.users?.length && onToggle(key), children: [_jsx("td", { className: "rp-table__name-cell rp-table__name-cell--bold", children: r.project_name }), _jsx("td", { className: "rp-table__muted", children: r.client_name }), _jsx("td", { children: r.currency }), _jsx("td", { className: "rp-table__num", children: fmtH(r.total_hours) }), _jsx("td", { className: "rp-table__num rp-table__num--accent", children: fmtH(r.uninvoiced_hours) }), _jsx("td", { className: "rp-table__num rp-table__num--accent", children: fmtAmt(r.uninvoiced_amount, r.currency) }), _jsx("td", { className: "rp-table__num", children: fmtAmt(r.uninvoiced_expenses, r.currency) }), _jsx("td", { className: "rp-table__expand-col", children: r.users?.length ? _jsx("button", { type: "button", className: "rp-table__expand-btn", "aria-expanded": isOpen, children: _jsx(IcoExpand, { open: isOpen }) }) : null })] }, key), isOpen && _jsx(UninvoicedUserRows, { users: r.users ?? [], currency: r.currency })] }));
                }) })] }));
}
