import { Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const CAL_SKEL_CELL_KEYS = Array.from({ length: 42 }, (_, i) => i);
export function TimesheetSkeleton({ layout = 'week', showChrome = true }) {
    const isCal = layout === 'calendar';
    const body = (_jsxs(_Fragment, { children: [_jsxs("div", { className: `tsp__strip${isCal ? ' tsp__strip--calendar' : ''}`, children: [isCal ? (_jsxs("div", { className: "tsp__cal tsp-skel__cal", children: [_jsx("div", { className: "tsp__cal-dows tsp-skel__cal-dows", children: CAL_SKEL_CELL_KEYS.slice(0, 7).map((i) => (_jsx("div", { className: `tsp__cal-dow${i >= 5 ? ' tsp__cal-dow--wknd' : ''}`, "aria-hidden": true, children: _jsx("span", { className: "tsp-skel__cal-dow" }) }, `dow-${i}`))) }), _jsx("div", { className: "tsp__cal-grid tsp-skel__cal-grid", children: CAL_SKEL_CELL_KEYS.map((i) => (_jsx("span", { className: "tsp-skel__cal-cell", style: { animationDelay: `${Math.min(i, 24) * 0.012}s` } }, `cell-${i}`))) })] })) : ([1, 2, 3, 4, 5, 6, 7].map((i) => (_jsxs("div", { className: "tsp__day tsp-skel__day", children: [_jsx("span", { className: "tsp-skel__day-wk" }), _jsx("span", { className: "tsp-skel__day-n" }), _jsx("div", { className: "tsp__day-bar-wrap", children: _jsx("span", { className: "tsp-skel__day-bar" }) }), _jsx("span", { className: "tsp-skel__day-h" })] }, i)))), _jsxs("div", { className: "tsp__wtotal tsp-skel__wtotal", children: [_jsx("span", { className: "tsp-skel__wtotal-lbl" }), _jsx("span", { className: "tsp-skel__wtotal-n" }), _jsx("div", { className: "tsp__wtotal-bar-wrap", children: _jsx("span", { className: "tsp-skel__wtotal-bar" }) }), _jsx("span", { className: "tsp-skel__wtotal-cap" })] })] }), _jsx("div", { className: "tsp__content", children: _jsx("div", { className: "tsp__groups", children: _jsx("div", { className: "tsp__group", children: _jsxs("div", { className: "tsp__rows", children: [[1, 2, 3].map((i) => (_jsxs("div", { className: "tsp__row tsp-skel__row", children: [_jsx("span", { className: "tsp-skel__row-bar" }), _jsxs("div", { className: "tsp__row-txt", children: [_jsx("span", { className: "tsp-skel__row-proj" }), _jsx("span", { className: "tsp-skel__row-task" }), _jsx("span", { className: "tsp-skel__row-notes" })] }), _jsxs("div", { className: "tsp__row-acts", children: [_jsx("span", { className: "tsp-skel__row-h" }), _jsx("span", { className: "tsp-skel__btn" }), _jsx("span", { className: "tsp-skel__btn" })] })] }, i))), _jsxs("div", { className: "tsp__day-sum tsp-skel__day-sum", children: [_jsx("span", { className: "tsp-skel__day-sum-add" }), _jsx("span", { className: "tsp-skel__day-sum-total" })] })] }) }) }) }), _jsxs("div", { className: "tsp__foot", children: [_jsxs("div", { className: "tsp__foot-total", children: [_jsx("span", { className: "tsp-skel__foot-lbl" }), _jsx("span", { className: "tsp-skel__foot-n" })] }), _jsx("div", { className: "tsp__submit-wrap", children: _jsx("span", { className: "tsp-skel__submit" }) })] })] }));
    if (!showChrome) {
        return (_jsx("div", { className: `tsp__body-skel tsp--skeleton${isCal ? ' tsp--skeleton--calendar tsp--calendar-layout' : ''}`, children: body }));
    }
    return (_jsxs("div", { className: `tsp tsp--skeleton${isCal ? ' tsp--skeleton--calendar' : ''}`, children: [_jsxs("div", { className: "tsp__top", children: [_jsxs("div", { className: "tsp__top-l", children: [_jsx("span", { className: "tsp-skel__arr" }), _jsx("span", { className: "tsp-skel__arr" }), _jsx("span", { className: "tsp-skel__heading" })] }), _jsx("div", { className: "tsp__top-r", children: _jsxs("div", { className: "tsp__seg tsp-skel__seg", children: [_jsx("span", { className: "tsp-skel__seg-btn" }), _jsx("span", { className: "tsp-skel__seg-btn" }), _jsx("span", { className: "tsp-skel__seg-btn" })] }) })] }), body] }));
}
