import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useI18n } from '@shared/i18n';
function Skel({ className }) {
    return _jsx("span", { className: `kl-ai-skel ${className}`, "aria-hidden": true });
}
export function KostaLegalAiSkeleton({ collapsed }) {
    const { t } = useI18n();
    return (_jsxs("div", { className: "kl-ai__layout kl-ai__layout--skeleton", "aria-busy": "true", "aria-live": "polite", "aria-label": t('common.loading'), children: [_jsxs("aside", { className: `kl-ai-sidebar kl-ai-sidebar--skeleton${collapsed ? ' kl-ai-sidebar--collapsed' : ''}`, children: [_jsxs("div", { className: "kl-ai-sidebar__head", children: [_jsx(Skel, { className: "kl-ai-skel--brand" }), _jsx(Skel, { className: "kl-ai-skel--collapse" })] }), _jsxs("nav", { className: "kl-ai-sidebar__nav", children: [_jsx("ul", { className: "kl-ai-sidebar__list", children: Array.from({ length: 7 }).map((_, i) => (_jsxs("li", { className: "kl-ai-sidebar__skel-row", children: [_jsx(Skel, { className: "kl-ai-skel--nav-icon" }), !collapsed ? _jsx(Skel, { className: `kl-ai-skel--nav-label kl-ai-skel--nav-label-${i % 3}` }) : null] }, `tool-${i}`))) }), _jsx("div", { className: "kl-ai-sidebar__divider kl-ai-skel--divider", "aria-hidden": true }), _jsx("ul", { className: "kl-ai-sidebar__list", children: Array.from({ length: 3 }).map((_, i) => (_jsxs("li", { className: "kl-ai-sidebar__skel-row", children: [_jsx(Skel, { className: "kl-ai-skel--nav-icon" }), !collapsed ? _jsx(Skel, { className: `kl-ai-skel--nav-label kl-ai-skel--nav-label-${(i + 1) % 3}` }) : null] }, `folder-${i}`))) })] }), _jsx("div", { className: "kl-ai-sidebar__foot", children: _jsx(Skel, { className: "kl-ai-skel--new-chat" }) })] }), _jsx("div", { className: "kl-ai__shell", children: _jsx("main", { className: "kl-ai__main", children: _jsxs("div", { className: "kl-ai__workspace kl-ai__workspace--skeleton", children: [_jsxs("div", { className: "kl-ai__hero kl-ai__hero--skeleton", children: [_jsx(Skel, { className: "kl-ai-skel--hero-title" }), _jsxs("div", { className: "kl-ai-skel--composer", children: [_jsx(Skel, { className: "kl-ai-skel--composer-input" }), _jsxs("div", { className: "kl-ai-skel--composer-toolbar", children: [_jsxs("div", { className: "kl-ai-skel--composer-tools", children: [_jsx(Skel, { className: "kl-ai-skel--tool-btn" }), _jsx(Skel, { className: "kl-ai-skel--tool-btn" }), _jsx(Skel, { className: "kl-ai-skel--filter" }), _jsx(Skel, { className: "kl-ai-skel--filter kl-ai-skel--filter-short" })] }), _jsx(Skel, { className: "kl-ai-skel--send" })] })] })] }), _jsxs("section", { className: "kl-ai__commands kl-ai__commands--skeleton", "aria-hidden": true, children: [_jsx(Skel, { className: "kl-ai-skel--section-title" }), _jsx(Skel, { className: "kl-ai-skel--section-sub" }), _jsx("ul", { className: "kl-ai__commands-grid", children: Array.from({ length: 8 }).map((_, i) => (_jsx("li", { children: _jsxs("div", { className: "kl-ai-skel--command-card", children: [_jsx(Skel, { className: "kl-ai-skel--command-icon" }), _jsx(Skel, { className: "kl-ai-skel--command-title" }), _jsx(Skel, { className: "kl-ai-skel--command-line" }), _jsx(Skel, { className: "kl-ai-skel--command-line kl-ai-skel--command-line-short" })] }) }, i))) })] })] }) }) })] }));
}
