export {
    getVacationKindCodes,
    getVacationKindLegend,
    listVacationScheduleEmployees,
    syncVacationScheduleEmployees,
    listVacationAbsenceDays,
    listVacationAttendanceMarkers,
    invalidateAttendanceMarkersCache,
    getVacationScheduleEmployee,
    postVacationScheduleImport,
    postVacationScheduleEmployee,
    patchVacationScheduleEmployee,
    deleteVacationScheduleEmployee,
    postVacationEmployeeAbsenceDay,
    patchVacationAbsenceDay,
    deleteVacationAbsenceDay,
    getVacationLeaveKinds,
    getVacationLeaveBalance,
    getVacationPartners,
    createVacationLeaveRequest,
    listVacationLeaveRequests,
    getVacationLeaveRequest,
    approveVacationLeaveRequest,
    declineVacationLeaveRequest,
    cancelVacationLeaveRequest,
    fetchVacationLeaveRequestPdfBlob,
    createVacationManualEntry,
    listVacationManualEntries,
    getVacationManualEntry,
    addVacationManualEntryDocuments,
    fetchVacationManualEntryDocumentBlob,
    deleteVacationManualEntryDocument,
    deleteVacationManualEntry,
    VACATION_LEAVE_REQUEST_KINDS,
    VACATION_LEAVE_REQUEST_STATUSES,
    VACATION_MANUAL_ENTRY_MAX_FILE_BYTES,
    VACATION_MANUAL_ENTRY_MAX_FILES,
    VACATION_MANUAL_ENTRY_ALLOWED_EXTENSIONS,
    type VacationScheduleEmployeeApi,
    type ListVacationScheduleEmployeesOptions,
    type VacationScheduleEmployeesSyncResultApi,
    type VacationAbsenceDayApi,
    type ListVacationAbsenceDaysOptions,
    type VacationAttendanceMarkerApi,
    type VacationAttendanceMarkerStatus,
    type VacationAbsenceDayItemApi,
    type VacationScheduleEmployeeDetailApi,
    type VacationScheduleImportResultApi,
    type VacationKindLegendItemApi,
    type VacationAbsenceDaySavedApi,
    type PostVacationScheduleEmployeeBody,
    type PatchVacationScheduleEmployeeBody,
    type VacationLeaveKindApi,
    type VacationLeaveBalanceApi,
    type VacationLeaveRequestKind,
    type VacationLeaveRequestStatus,
    type VacationPartnerApi,
    type VacationLeaveRequestApi,
    type CreateVacationLeaveRequestBody,
    type ListVacationLeaveRequestsOptions,
    type VacationManualEntryApi,
    type VacationManualEntryDocumentApi,
    type CreateVacationManualEntryInput,
    type ListVacationManualEntriesOptions,
} from './api';
