import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createPortal } from 'react-dom';
import { useMemo } from 'react';
import { sortByRuLabel, userPickerSortLabel } from '@shared/lib/sortByRuLabel';
import { useInventory } from '../model';
export function AssignModal() {
    const { assignModal, setAssignModal, assignUserId, setAssignUserId, formError, submitting, users, handleAssignSubmit, } = useInventory();
    const sortedUsers = useMemo(() => sortByRuLabel(users, userPickerSortLabel), [users]);
    if (!assignModal)
        return null;
    const content = (_jsx("div", { className: "inv__overlay", role: "dialog", "aria-modal": "true", children: _jsxs("div", { className: "inv__modal", onClick: (e) => e.stopPropagation(), children: [_jsxs("div", { className: "inv__modal-head", children: [_jsx("h3", { className: "inv__modal-title", children: "\u0417\u0430\u043A\u0440\u0435\u043F\u0438\u0442\u044C \u0437\u0430 \u0441\u043E\u0442\u0440\u0443\u0434\u043D\u0438\u043A\u043E\u043C" }), _jsx("button", { type: "button", className: "inv__modal-close", onClick: () => setAssignModal(null), children: _jsxs("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("line", { x1: "18", y1: "6", x2: "6", y2: "18" }), _jsx("line", { x1: "6", y1: "6", x2: "18", y2: "18" })] }) })] }), _jsxs("p", { className: "inv__modal-desc", children: [assignModal.name, " (\u0438\u043D\u0432. ", assignModal.inventory_number, ")"] }), formError && _jsx("p", { className: "inv__form-err", children: formError }), _jsxs("form", { onSubmit: handleAssignSubmit, className: "inv__form", children: [_jsxs("label", { className: "inv__form-field", children: [_jsx("span", { className: "inv__form-label", children: "\u0421\u043E\u0442\u0440\u0443\u0434\u043D\u0438\u043A" }), _jsxs("select", { className: "inv__input", value: assignUserId === '' ? '' : assignUserId, onChange: (e) => setAssignUserId(e.target.value === '' ? '' : Number(e.target.value)), required: true, children: [_jsx("option", { value: "", children: "\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435" }), sortedUsers.map((u) => (_jsx("option", { value: u.id, children: u.display_name || u.email }, u.id)))] })] }), _jsxs("div", { className: "inv__modal-foot", children: [_jsx("button", { type: "button", className: "inv__btn inv__btn--ghost", onClick: () => setAssignModal(null), disabled: submitting, children: "\u041E\u0442\u043C\u0435\u043D\u0430" }), _jsx("button", { type: "submit", className: "inv__btn inv__btn--primary", disabled: submitting || assignUserId === '', children: "\u0417\u0430\u043A\u0440\u0435\u043F\u0438\u0442\u044C" })] })] })] }) }));
    return typeof document !== 'undefined' ? createPortal(content, document.body) : null;
}
