import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createPortal } from 'react-dom';
import { useInventory } from '../model';
export function CategoryModal() {
    const ctx = useInventory();
    const { categoryModal, setCategoryModal, categoryForm, setCategoryForm, formError, submitting, handleCategorySubmit, } = ctx;
    if (!categoryModal)
        return null;
    const content = (_jsx("div", { className: "inv__overlay", role: "dialog", "aria-modal": "true", children: _jsxs("div", { className: "inv__modal", onClick: (e) => e.stopPropagation(), children: [_jsxs("div", { className: "inv__modal-head", children: [_jsx("h3", { className: "inv__modal-title", children: categoryModal === 'add' ? 'Новая категория' : 'Изменить категорию' }), _jsx("button", { type: "button", className: "inv__modal-close", onClick: () => setCategoryModal(null), children: _jsxs("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("line", { x1: "18", y1: "6", x2: "6", y2: "18" }), _jsx("line", { x1: "6", y1: "6", x2: "18", y2: "18" })] }) })] }), formError && _jsx("p", { className: "inv__form-err", children: formError }), _jsxs("form", { onSubmit: handleCategorySubmit, className: "inv__form", children: [_jsxs("label", { className: "inv__form-field", children: [_jsx("span", { className: "inv__form-label", children: "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435" }), _jsx("input", { className: "inv__input", value: categoryForm.name, onChange: (e) => setCategoryForm((f) => ({ ...f, name: e.target.value })), required: true })] }), _jsxs("label", { className: "inv__form-field", children: [_jsx("span", { className: "inv__form-label", children: "\u041E\u043F\u0438\u0441\u0430\u043D\u0438\u0435" }), _jsx("textarea", { className: "inv__input", rows: 2, value: categoryForm.description, onChange: (e) => setCategoryForm((f) => ({ ...f, description: e.target.value })) })] }), _jsxs("div", { className: "inv__modal-foot", children: [_jsx("button", { type: "button", className: "inv__btn inv__btn--ghost", onClick: () => setCategoryModal(null), disabled: submitting, children: "\u041E\u0442\u043C\u0435\u043D\u0430" }), _jsx("button", { type: "submit", className: "inv__btn inv__btn--primary", disabled: submitting, children: "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C" })] })] })] }) }));
    return typeof document !== 'undefined' ? createPortal(content, document.body) : null;
}
