import type { Translations } from '@docx-editor.dev/i18n';

/**
 * Russian chrome strings for `@docx-editor.dev`.
 * Upstream has no `ru` locale yet — omitted keys fall back to English.
 */
export const docxEditorRu: Translations = {
    _lang: 'ru',
    common: {
        cancel: 'Отмена',
        apply: 'Применить',
        close: 'Закрыть',
        comment: 'Комментарий',
        dismiss: 'Скрыть',
    },
    toolbar: {
        ariaLabel: 'Панель форматирования',
        file: 'Файл',
        format: 'Формат',
        insert: 'Вставка',
        review: 'Рецензирование',
        open: 'Открыть',
        openShortcut: 'Ctrl+O',
        save: 'Сохранить',
        saveShortcut: 'Ctrl+S',
        print: 'Печать',
        printShortcut: 'Ctrl+P',
        pageSetup: 'Параметры страницы',
        leftToRight: 'Текст слева направо',
        rightToLeft: 'Текст справа налево',
        image: 'Изображение',
        table: 'Таблица',
        insertTable: 'Вставить таблицу',
        break: 'Разрыв',
        insertFootnote: 'Вставить сноску',
        insertEndnote: 'Вставить концевую сноску',
        pageBreak: 'Разрыв страницы',
        sectionBreakNextPage: 'Разрыв раздела (со следующей страницы)',
        sectionBreakContinuous: 'Разрыв раздела (на текущей странице)',
        tableOfContents: 'Оглавление',
        watermark: 'Подложка',
        help: 'Справка',
        reportIssue: 'Сообщить о проблеме',
    },
    toc: {
        refresh: 'Обновить оглавление',
        refreshPageNumbers: 'Обновить номера страниц',
    },
    formattingBar: {
        groups: {
            history: 'История',
            zoom: 'Масштаб',
            styles: 'Стили',
            font: 'Шрифт',
            textFormatting: 'Форматирование текста',
            script: 'Индексы',
            alignment: 'Выравнивание',
            listFormatting: 'Списки',
            format: 'Формат',
            image: 'Изображение',
            table: 'Таблица',
        },
        undo: 'Отменить',
        undoShortcut: 'Отменить (Ctrl+Z)',
        redo: 'Повторить',
        redoShortcut: 'Повторить (Ctrl+Y)',
        bold: 'Жирный',
        boldShortcut: 'Жирный (Ctrl+B)',
        italic: 'Курсив',
        italicShortcut: 'Курсив (Ctrl+I)',
        underline: 'Подчёркнутый',
        underlineShortcut: 'Подчёркнутый (Ctrl+U)',
        strikethrough: 'Зачёркнутый',
        fontColor: 'Цвет шрифта',
        highlightColor: 'Цвет выделения',
        insertLink: 'Вставить ссылку',
        insertLinkShortcut: 'Вставить ссылку (Ctrl+K)',
        superscript: 'Надстрочный',
        superscriptShortcut: 'Надстрочный (Ctrl+Shift+=)',
        subscript: 'Подстрочный',
        subscriptShortcut: 'Подстрочный (Ctrl+=)',
        imageProperties: 'Свойства изображения',
        imagePropertiesShortcut: 'Свойства изображения (альтернативный текст, граница)…',
        imageWrap: 'Обтекание текстом',
        altText: 'Альтернативный текст',
        clearFormatting: 'Очистить форматирование',
        formatPainter: 'Формат по образцу',
        formatPainterShortcut: 'Формат по образцу (Ctrl+Alt+C, Ctrl+Alt+V)',
        commentsAndChanges: 'Комментарии и изменения',
        more: 'Ещё',
        unavailableInPreview: 'Недоступно в этой предварительной версии',
        paragraphMarks: 'Показать знаки абзацев',
    },
    alignment: {
        alignLeft: 'По левому краю',
        alignLeftShortcut: 'Ctrl+L',
        center: 'По центру',
        centerShortcut: 'Ctrl+E',
        alignRight: 'По правому краю',
        alignRightShortcut: 'Ctrl+R',
        justify: 'По ширине',
        justifyShortcut: 'Ctrl+J',
    },
    lists: {
        ariaLabel: 'Форматирование списков',
        typeAriaLabel: 'Тип списка',
        indentationAriaLabel: 'Отступ списка',
        bulletList: 'Маркированный список',
        numberedList: 'Нумерованный список',
        decreaseIndent: 'Уменьшить отступ',
        increaseIndent: 'Увеличить отступ',
    },
    lineSpacing: {
        label: 'Межстрочный интервал',
        single: 'Одинарный',
        double: 'Двойной',
        lineSpacingTitle: 'Межстрочный интервал: {label}',
        blockSpacingRules: 'Интервал абзаца',
        addSpaceBefore: 'Добавить интервал перед абзацем',
        removeSpaceBefore: 'Убрать интервал перед абзацем',
        addSpaceAfter: 'Добавить интервал после абзаца',
        removeSpaceAfter: 'Убрать интервал после абзаца',
        options: 'Параметры межстрочного интервала…',
    },
    styles: {
        selectAriaLabel: 'Выбрать стиль абзаца',
        normalText: 'Обычный текст',
        title: 'Заголовок',
        subtitle: 'Подзаголовок',
        heading1: 'Заголовок 1',
        heading2: 'Заголовок 2',
        heading3: 'Заголовок 3',
    },
    font: {
        selectAriaLabel: 'Выбрать шрифт',
        sansSerif: 'Без засечек',
        serif: 'С засечками',
        monospace: 'Моноширинный',
        documentFonts: 'Шрифты документа',
    },
    fontSize: {
        decrease: 'Уменьшить размер шрифта',
        increase: 'Увеличить размер шрифта',
        label: 'Размер шрифта',
        listLabel: 'Размеры шрифта',
    },
    zoom: {
        ariaLabel: 'Масштаб: {label}',
        zoomOut: 'Уменьшить',
        zoomIn: 'Увеличить',
        zoomLevel: 'Уровень масштаба',
        automatic: 'Автоматически',
        fitWidth: 'По ширине',
    },
    colorPicker: {
        highlightColors: 'Цвета выделения',
        customColor: 'Свой цвет',
        noColor: 'Без цвета',
        automatic: 'Авто',
        themeColors: 'Цвета темы',
        theme: {
            background1: 'Фон 1',
            text1: 'Текст 1',
            background2: 'Фон 2',
            text2: 'Текст 2',
            accent1: 'Акцент 1',
            accent2: 'Акцент 2',
            accent3: 'Акцент 3',
            accent4: 'Акцент 4',
            accent5: 'Акцент 5',
            accent6: 'Акцент 6',
        },
        standardColors: 'Стандартные цвета',
        colors: {
            black: 'Чёрный',
            darkRed: 'Тёмно-красный',
            red: 'Красный',
            orange: 'Оранжевый',
            yellow: 'Жёлтый',
            darkYellow: 'Тёмно-жёлтый',
            green: 'Зелёный',
            darkGreen: 'Тёмно-зелёный',
            blue: 'Синий',
            darkBlue: 'Тёмно-синий',
            purple: 'Фиолетовый',
            white: 'Белый',
            lightGreen: 'Светло-зелёный',
            lightBlue: 'Голубой',
            darkGray: 'Тёмно-серый',
            cyan: 'Бирюзовый',
            darkCyan: 'Тёмно-бирюзовый',
            magenta: 'Пурпурный',
            darkMagenta: 'Тёмно-пурпурный',
            lightGray: 'Светло-серый',
            brightGreen: 'Ярко-зелёный',
        },
        apply: 'Применить',
    },
    dialogs: {
        imageProperties: {
            title: 'Свойства изображения',
            altText: 'Альтернативный текст',
            altTextPlaceholder: 'Опишите изображение для доступности…',
            textWrapping: 'Обтекание текстом',
            dimensions: 'Размеры',
            widthLabel: 'Ширина:',
            heightLabel: 'Высота:',
            lockAspectRatio: 'Сохранять пропорции',
        },
        pageSetup: {
            title: 'Параметры страницы',
            pageSize: 'РАЗМЕР СТРАНИЦЫ',
            sizeLabel: 'Размер',
            custom: 'Другой',
            orientation: 'Ориентация',
            portrait: 'Книжная',
            landscape: 'Альбомная',
            margins: 'ПОЛЯ',
            top: 'Верхнее',
            bottom: 'Нижнее',
            left: 'Левое',
            right: 'Правое',
            applyTo: 'Применить к',
            applyToDocument: 'Всему документу',
            applyToSection: 'Этому разделу',
        },
        paragraph: {
            title: 'Абзац',
            general: 'Общие',
            alignment: 'Выравнивание',
            alignLeft: 'По левому краю',
            alignCenter: 'По центру',
            alignRight: 'По правому краю',
            alignJustify: 'По ширине',
            indentation: 'Отступ',
            spacing: 'Интервал',
            ok: 'ОК',
            cancel: 'Отмена',
        },
    },
    contextMenu: {
        ariaLabel: 'Контекстное меню',
        cut: 'Вырезать',
        cutShortcut: 'Ctrl+X',
        copy: 'Копировать',
        copyShortcut: 'Ctrl+C',
        paste: 'Вставить',
        pasteShortcut: 'Ctrl+V',
        pasteWithoutFormatting: 'Вставить без форматирования',
        pasteWithoutFormattingShortcut: 'Ctrl+Shift+V',
        copyFormatting: 'Копировать форматирование',
        copyFormattingShortcut: 'Ctrl+Alt+C',
        pasteFormatting: 'Вставить форматирование',
        pasteFormattingShortcut: 'Ctrl+Alt+V',
        delete: 'Удалить',
        deleteShortcut: 'Del',
        selectAll: 'Выделить всё',
        selectAllShortcut: 'Ctrl+A',
        editCustomNode: 'Изменить {label}',
        removeCustomNode: 'Удалить {label}',
    },
    titleBar: {
        untitled: 'Без названия',
        documentNameAriaLabel: 'Имя документа',
        menuBarAriaLabel: 'Строка меню',
    },
    errors: {
        unableToParse: 'Не удалось разобрать документ',
        somethingWentWrong: 'Что-то пошло не так',
        errorDescription:
            'При отображении этого компонента произошла ошибка. Попробуйте ещё раз или обратитесь в поддержку, если проблема сохраняется.',
        errorLabel: 'Ошибка:',
        componentStack: 'Стек компонента:',
        tryAgain: 'Повторить',
        showDetails: 'Показать подробности',
        hideDetails: 'Скрыть подробности',
    },
    table: {
        insertRowAbove: 'Вставить строку выше',
        insertRowBelow: 'Вставить строку ниже',
        insertColumnLeft: 'Вставить столбец слева',
        insertColumnRight: 'Вставить столбец справа',
        deleteRow: 'Удалить строку',
        deleteColumn: 'Удалить столбец',
        deleteTable: 'Удалить таблицу',
        selectTable: 'Выделить всю таблицу',
        mergeCells: 'Объединить ячейки',
        splitCell: 'Разделить ячейку',
        editingTools: 'Инструменты таблицы',
        label: 'Таблица:',
        cellFillColor: 'Заливка ячейки',
        borderColor: 'Цвет границы',
        borderWidth: 'Толщина границы',
        clearCellFill: 'Убрать заливку',
        moreOptions: 'Другие параметры таблицы',
        borders: {
            all: 'Все границы',
            outside: 'Внешние границы',
            inside: 'Внутренние границы',
            none: 'Без границ',
            top: 'Верхняя граница',
            bottom: 'Нижняя граница',
            left: 'Левая граница',
            right: 'Правая граница',
            styleAriaLabel: 'Стиль границы',
            tooltip: 'Границы',
        },
    },
    tableAdvanced: {
        verticalAlignment: 'Вертикальное выравнивание',
        top: 'По верху',
        middle: 'Посередине',
        bottom: 'По низу',
        tableProperties: 'Свойства таблицы…',
        tableAlignment: 'Выравнивание таблицы',
        alignTableLeft: 'Таблица слева',
        alignTableCenter: 'Таблица по центру',
        alignTableRight: 'Таблица справа',
    },
    hyperlinkPopup: {
        displayTextPlaceholder: 'Отображаемый текст',
        urlPlaceholder: 'https://example.com',
        urlLabel: 'URL',
        copyLink: 'Копировать ссылку',
        editLink: 'Изменить ссылку',
        removeLink: 'Удалить ссылку',
        openLink: 'Открыть ссылку',
        apply: 'Применить',
        cancel: 'Отмена',
        insertTitle: 'Вставить ссылку',
        editTitle: 'Изменить ссылку',
        bookmarkTarget: 'Переход к месту в этом документе',
        refused: 'Не удалось применить ссылку. Проверьте адрес и попробуйте снова.',
    },
    editor: {
        showDocumentOutline: 'Показать структуру документа',
        linkCopied: 'Ссылка скопирована в буфер обмена',
        fontSubstitutionNotice: 'Некоторые шрифты документа недоступны, показаны замены: {fonts}',
    },
    loading: {
        label: 'Загрузка',
    },
    viewer: {
        pageIndicator: '{current} из {total}',
    },
    headerFooter: {
        chromeAriaLabel: 'Редактирование колонтитулов',
        header: 'Верхний колонтитул',
        footer: 'Нижний колонтитул',
        options: 'Параметры',
        differentFirstPage: 'Особый для первой страницы',
        differentOddEven: 'Разные для чётных и нечётных',
        linkToPrevious: 'Как в предыдущем разделе',
        unlinkFromPrevious: 'Отвязать от предыдущего',
        insertPageNumber: 'Вставить номер страницы',
        insertTotalPages: 'Вставить число страниц',
        removeHeader: 'Удалить верхний колонтитул',
        removeFooter: 'Удалить нижний колонтитул',
    },
    imageWrap: {
        inline: 'В тексте',
        square: 'Квадрат',
        tight: 'По контуру',
        through: 'Сквозное',
        floatLeft: 'Квадрат слева',
        floatRight: 'Квадрат справа',
        topAndBottom: 'Сверху и снизу',
        behindText: 'За текстом',
        inFrontOfText: 'Перед текстом',
        tooltipPrefix: 'Обтекание: {label}',
    },
    imageAltText: {
        panelTitle: 'Альтернативный текст',
        title: 'Заголовок',
        description: 'Описание',
    },
    comments: {
        unknown: 'Неизвестно',
        addComment: 'Добавить комментарий…',
        replyPlaceholder: 'Ответить или отметить других через @',
        resolve: 'Решить',
        reopen: 'Открыть снова',
    },
    review: {
        displayForReview: 'Отображение для проверки',
        allMarkup: 'Вся разметка',
        noMarkup: 'Без разметки',
        original: 'Исходный',
        previousChange: 'Предыдущее изменение',
        nextChange: 'Следующее изменение',
        acceptAllChanges: 'Принять все изменения',
        rejectAllChanges: 'Отклонить все изменения',
        ariaLabel: 'Рецензирование',
        empty: 'Нет изменений и комментариев',
        accept: 'Принять',
        reject: 'Отклонить',
        deleteComment: 'Удалить комментарий',
        discardChange: 'Отменить изменение',
        reply: 'Ответить',
        inserted: 'Добавлено',
        deleted: 'Удалено',
        showPane: 'Показать комментарии',
        resolved: 'Решено',
    },
    editingMode: {
        label: 'Режим редактирования',
        editing: 'Редактирование',
        editingHint: 'Изменять документ напрямую',
        suggesting: 'Предложения',
        suggestingHint: 'Правки становятся предложениями',
        viewing: 'Просмотр',
        viewingHint: 'Только чтение, без правок',
    },
    navigation: {
        ariaLabel: 'Навигация по документу',
        title: 'Навигация',
        openAriaLabel: 'Открыть навигацию',
        openTitle: 'Навигация',
        closeAriaLabel: 'Закрыть навигацию',
        closeTitle: 'Закрыть навигацию',
        tabs: {
            headings: 'Заголовки',
            find: 'Поиск',
        },
        find: {
            placeholder: 'Поиск по документу',
            inputAriaLabel: 'Поиск по документу',
            clearAriaLabel: 'Очистить поиск',
            previousAriaLabel: 'Предыдущий результат',
            nextAriaLabel: 'Следующий результат',
            matchCase: 'Учитывать регистр',
            wholeWord: 'Только слова целиком',
            noResults: 'Ничего не найдено',
            searching: 'Поиск…',
            counter: 'Результат {current} из {total}',
        },
    },
    disabledReason: {
        editorNotReady: 'Редактор ещё не готов',
        viewing: 'Документ открыт только для просмотра',
        noDocument: 'Документ не загружен',
        unavailable: 'Команда недоступна',
    },
};
